/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VISTA;

import Controlador.ControladorUsuario;
import MODELO.Usuario;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.WindowConstants;

/**
 *
 * @author User
 */
public class Formulario extends javax.swing.JFrame {

    private ControladorUsuario controlador;
    private Usuario usuarioActual;
    
    public Formulario() {
        iniComponents();
        controlador = new ControladorUsuario();
    }

    private void iniComponents() {
        JLabel lblNombre = new JLabel("Nombre:");
        JLabel lblTipo = new JLabel("Tipo Usuario:");
        txtNombre = new JTextField(20);
        txtTipoUsuario = new JTextField(20);

        btnA = new JButton("Aceptar");
        btnC = new JButton("Cancelar");
        btnR = new JButton("Registrar");

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setTitle("Formulario Usuario");
        setLayout(null);

        // Posiciones
        lblNombre.setBounds(30, 30, 100, 25);
        txtNombre.setBounds(130, 30, 200, 25);

        lblTipo.setBounds(30, 70, 100, 25);
        txtTipoUsuario.setBounds(130, 70, 200, 25);

        btnA.setBounds(30, 120, 60, 30);
        btnC.setBounds(110, 120, 60, 30);
        btnR.setBounds(190, 120, 60, 30);

        // Añadir componentes
        add(lblNombre);
        add(txtNombre);
        add(lblTipo);
        add(txtTipoUsuario);
        add(btnA);
        add(btnC);
        add(btnR);

        setSize(400, 220);
        setLocationRelativeTo(null);

        // Botón A (crear con Factory)
        btnA.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                if (camposValidos()) {
                    usuarioActual = controlador.crearUsuario(txtNombre.getText(), txtTipoUsuario.getText());
                    JOptionPane.showMessageDialog(null, "Usuario creado:\n" + usuarioActual);
                } else {
                    JOptionPane.showMessageDialog(null, "Complete todos los campos");
                }
            }
        });

        // Botón C (limpia)
        btnC.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                txtNombre.setText("");
                txtTipoUsuario.setText("");
            }
        });

        // Botón R (registrar con Facade)
        btnR.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                if (camposValidos()) {
                    Usuario u = controlador.crearUsuario(txtNombre.getText(), txtTipoUsuario.getText());
                    boolean exito = controlador.registrarUsuario(u);
                    if (exito) {
                        JOptionPane.showMessageDialog(null, "Usuario registrado correctamente");
                    } else {
                        JOptionPane.showMessageDialog(null, "Error al registrar usuario");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Complete todos los campos");
                }
            }
        });
    }

    private boolean camposValidos() {
        return !txtNombre.getText().isEmpty() && !txtTipoUsuario.getText().isEmpty();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtTipoUsuario = new javax.swing.JTextField();
        btnA = new javax.swing.JButton();
        btnC = new javax.swing.JButton();
        btnR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre:");

        jLabel2.setText("Tipo Usuario");

        btnA.setText("Agregar");

        btnC.setText("Cancelar");

        btnR.setText("Registrar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnA))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                        .addComponent(btnR))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtNombre)
                        .addComponent(txtTipoUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)))
                .addContainerGap(197, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnA)
                    .addComponent(btnC)
                    .addComponent(btnR))
                .addGap(80, 80, 80))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnA;
    private javax.swing.JButton btnC;
    private javax.swing.JButton btnR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTipoUsuario;
    // End of variables declaration//GEN-END:variables
}
